[package]
name = "web_test"
version = "0.1.0"
authors = ["Phoenix <kahlo.phoenix@gmail.com>"]

[dependencies]
simple-server = "0.3.0"
file = "1.1.1"
lazy_static = "1.0.0"
time = "0.1.39"
serde = "1.0.37"
serde_json = "1.0"
serde_derive = "1.0.37"
walkdir = "2"
